#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ft8006m_with_ktd2151_dsi_vdo_h570tax0_ns570hd3901az01_rx_mx2532e_ztr_s562z.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/



